version: '3'
services:
  db:
    image: postgresql
    build:
      context: .
      dockerfile: ./basedados/Dockerfile
    environment:
      POSTGRES_DB: go
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
  app:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    command: ["go", "run", "main"]
    depends_on:
      - db
    links:
      - db